[platformio]
boards_dir = board_def/boards

[env:gas_analyser_m0]
platform = atmelsam
board = gas_analyser_m0
framework = arduino
board_build.variants_dir = board_def/variants
debug_tool = atmel-ice
;upload_protocol = atmel-ice
build_flags =
    -D USE_TINYUSB=0
    -D SERIAL_RX_BUFFER_SIZE=512
    -fstack-usage
    -Wstack-usage=512